### ISSUE TITLE
Gradio内置队列报错

### ISSUE THREAD

**Issue by XiaoCC** [rauldlnx10/sd-webui-swap-mukham#11]
a
Traceback (most recent call last):
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\launch.py", line 48, in <module>
    main()
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\launch.py", line 44, in main
    start()
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\modules\launch_utils.py", line 436, in start
    webui.webui()
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\webui.py", line 79, in webui
    app, local_url, share_url = shared.demo.launch(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1858, in launch
    self.validate_queue_settings()
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1702, in validate_queue_settings
    raise ValueError(
ValueError: Queue needs to be enabled! You may get this error by either 1) passing a function that uses the yield keyword into an interface without enabling the queue or 2) defining an event that cancels another event without enabling the queue. Both can be solved by calling .queue() before .launch()
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Loading VAE weights specified in settings: D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: xformers... done.
Model loaded in 13.4s (load weights from disk: 1.3s, create model: 0.4s, apply weights to model: 9.6s, load VAE: 1.8s, calculate empty prompt: 0.1s).

--------

[程序崩溃，退出代码为 1 (0x00000001)]

你好，以上是错误信息，我停用了Gradio的内置队列，应为启用这个功能会导致很多页面刷新上的错误，请问插件能否支持兼容停用了Gradio的内置队列，谢谢！

**Comment by XiaoCC** [comment]
![image](https://github.com/rauldlnx10/sd-webui-swap-mukham/assets/7299222/31edf539-bfa5-44e1-b453-5cb459445da5)
