### ISSUE TITLE
Last update breaks automatic1111 gui for me

### ISSUE THREAD

**Issue by nachodha** [rauldlnx10/sd-webui-swap-mukham#4]
Updating to last version of this repo results in this error every time i launch the GUI

Traceback (most recent call last):
  File "D:\A1111\stable-diffusion-webui\launch.py", line 39, in <module>
    main()
  File "D:\A1111\stable-diffusion-webui\launch.py", line 35, in main
    start()
  File "D:\A1111\stable-diffusion-webui\modules\launch_utils.py", line 390, in start
    import webui
  File "D:\A1111\stable-diffusion-webui\webui.py", line 44, in <module>
    import gradio  # noqa: F401
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 34, in <module>
    from gradio_client import media_data
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio_client\__init__.py", line 1, in <module>
    from gradio_client.client import Client
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio_client\client.py", line 24, in <module>
    from huggingface_hub import CommitOperationAdd, SpaceHardware, SpaceStage
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\__init__.py", line 322, in __getattr__
    submod = importlib.import_module(submod_path)
  File "C:\Users\pakok\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\hf_api.py", line 35, in <module>
    from huggingface_hub.utils import (
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\__init__.py", line 18, in <module>
    from . import tqdm as _tqdm  # _tqdm is the module
  File "D:\A1111\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\tqdm.py", line 63, in <module>
    from tqdm.auto import tqdm as old_tqdm
ModuleNotFoundError: No module named 'tqdm.auto'

Only solution i found is to reinstall venv and launch automatic1111 without sd-webui-swap-mukham extension. It seems like if its overriding tdqm

**Comment by nachodha** [comment]
Reinstalled this commit b04ac9c3673209c233e47d0bbc90330af4782e08  and works perfect, updated again just to check the error and indeed, same error after last update.

**Comment by rauldlnx10** [comment]
> Reinstalled this commit [b04ac9c](https://github.com/rauldlnx10/sd-webui-swap-mukham/commit/b04ac9c3673209c233e47d0bbc90330af4782e08) and works perfect, updated again just to check the error and indeed, same error after last update.

Try reinstalling moviepy, i think it gives a conflict.

**Comment by ivanoff13** [comment]
> 
Go to venv / scripts, open cmd and write:
activate
pip install --upgrade moviepy

this action did not work(

**Comment by ivanoff13** [comment]
ImportError: cannot import name 'auto' from 'tqdm' (E:\seait_installers_version_0.1.1\stable-diffusion-webui\venv\lib\site-packages\tqdm\__init__.py)

**Comment by rauldlnx10** [comment]
I´ve deleted my venv folder to make a clean install and try to reproduce the error... Ill try to find a solution.

**Comment by rauldlnx10** [comment]
> ImportError: cannot import name 'auto' from 'tqdm' (E:\seait_installers_version_0.1.1\stable-diffusion-webui\venv\lib\site-packages\tqdm__init__.py)

The problem is the program requires a newer version of tdqm.
Go to venv / scripts, open cmd and write:
activate
pip install moviepy==1.0.3
pip install tqdm==4.65.0

this solved the problem for me, ill add tdqm in the requirements.txt file.

**Comment by ivanoff13** [comment]
> > Ошибка импорта: не удается импортировать имя 'auto' из 'tqdm' (E:\seait_installers_version_0.1.1\stable-diffusion-webui\venv\lib\site-packages\tqdm__init__.py)
> 
> Проблема в том, что программе требуется более новая версия tdqm. Перейдите в venv / scripts, откройте cmd и напишите: активировать pip install moviepy==1.0.3 pip install tqdm == 4.65.0
> 
> это решило проблему для меня, я добавлю tdqm в файл requirements.txt.

this solved the problem!now it remains to record a video instruction))

**Comment by rauldlnx10** [comment]
> > > Ошибка импорта: не удается импортировать имя 'auto' из 'tqdm' (E:\seait_installers_version_0.1.1\stable-diffusion-webui\venv\lib\site-packages\tqdm__init__.py)
> > 
> > 
> > Проблема в том, что программе требуется более новая версия tdqm. Перейдите в venv / scripts, откройте cmd и напишите: активировать pip install moviepy==1.0.3 pip install tqdm == 4.65.0
> > это решило проблему для меня, я добавлю tdqm в файл requirements.txt.
> 
> this solved the problem!now it remains to record a video instruction))

Can you explain what you mean with video instruction?
